### ISSUE TITLE
难道回调不需要transaction_id

### ISSUE THREAD

**Issue by justcy** [boyuanitsm/pay#4]
抱歉，我找了代码没有发现异步回调的时候保存 transaction_id 的代码，难道是没有处理？还是我没有找对？

**Comment by co-kevin** [comment]
这个 transaction_id 是哪个平台的？

**Comment by justcy** [comment]
微信

**Comment by hueyzng** [comment]
这个 transaction_id 对应的微信支付官方文档是？

**Comment by co-kevin** [comment]
https://github.com/boyuanitsm/pay/blob/3241a93f0ac6da7d60d0305c94de472af564dcaf/src/test/java/com/boyuanitsm/pay/rest/WeChatResource.java#L105

这个方法的请求参数里会有

我又看了下序列化的实体，确实没有接收  transaction_id ，可能由于当时写这个库的时候微信并没有这个参数，自行写一个实体继承 UnifiedOrderReqData，在里面加上这个字段就行了。也欢迎提 PR https://github.com/boyuanitsm/pay/blob/3241a93f0ac6da7d60d0305c94de472af564dcaf/src/main/java/com/boyuanitsm/pay/wxpay/protocol/unified_order_protocol/UnifiedOrderReqData.java#L31
